[package]
name = "trie_rs"
version = "0.0.1"
edition = "2021"
license = "Redis Source Available License 2.0 (RSALv2) or the Server Side Public License v1 (SSPLv1)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
redis_allocator = []

[lib]
crate-type = ["staticlib"]
name = "trie_rs"
